<div style="background-color:rgb(255, 255, 200);">
    
**File name: lect02-example.ipynb**

**Author: Du Huynh**

A small example showing **stratified sampling**.

March 2022</span>
</div>

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
# synthesize some a X matrix having 2 feature columns and 15 instances.
X = np.arange(30).reshape((15, 2))

# synthesize an array containing the class labels. There are two labels: 0 and 1.
# This is an imbalanced dataset, as we have 10 instances in class 0 and only 5 instances
# in class 1.
y = np.array([0,0,0,0,0,0,0,0,0,0,1,1,1,1,1])

For the cell below, try the following:

1. Run the cell a few times. You should see the training and test sets are different each time.

1. Next, insert the optional argument `random_state=42` (you can replace `42` by a different random seed also). Run the cell again a few times. You should see the same instances being assigned to the training and test sets.

   In the experiments in Steps 1 and 2 above, pay attention also to the last two numbers output by the `print` statements. The two numbers are usually different in each run.

1. Replace the call to the `train_test_split` function as follows:

   <code>X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)</code>

   Here, we use the `stratify` argument to indicate that we want **stratified sampling**, i.e., we want the training set and the test set to preserve as much as possible the ratio of the number of instances of class 0 and class 1. In our `y` array, the number of class 0 instances is 2/3 (or 0.6666) of the total number of instances. In Step 3 above, run the cell a few times and you should see `0.6666666666666666` as the outputs from the two `print` statements.

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print('X_train ='), print(X_train)
print('X_test ='), print(X_test)
print('y_train ='), print(y_train)
print('y_test ='), print(y_test)

print(np.sum(y_train==0)/len(y_train))
print(np.sum(y_test==0)/len(y_test))

X_train =
[[ 2  3]
 [28 29]
 [10 11]
 [22 23]
 [26 27]
 [18 19]
 [12 13]
 [24 25]
 [ 4  5]
 [ 6  7]
 [16 17]
 [20 21]]
X_test =
[[ 0  1]
 [14 15]
 [ 8  9]]
y_train =
[0 1 0 1 1 0 0 1 0 0 0 1]
y_test =
[0 0 0]
0.5833333333333334
1.0
